language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
env:
  - DATABASE_URL=tri.db
    RUST_BACKTRACE=1
install:
  - cargo install diesel_cli --no-default-features --features sqlite
  - cargo install just
script:
  - just travis-ci
