language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx
install:
  - cargo install diesel_cli --no-default-features --features sqlite
  - cargo install just
script:
  - just travis-ci
