CREATE TABLE tasks (
	id INTEGER NOT NULL PRIMARY KEY,
	name TEXT NOT NULL,
	create_date DATE NOT NULL DEFAULT CURRENT_DATE,
	due_date DATE,
	priority INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	done BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE users (
	id INTEGER NOT NULL PRIMARY KEY,
	slack_id TEXT NOT NULL UNIQUE,
	name TEXT
);
